import gif from "../assets/images/image.gif";
7;

export const youtubeData = [
  {
    video: {
      videoId: "sNf0o51-l7o&ab_channel=DYNAMIXFITNESSUK",
      title: "Tricep Assisted Dip Machine",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/sNf0o51-l7o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBGGnzonNVrZWag6ORqai5wXmdxQQ",
        },
      ],
      channelName: "DYNAMIX FITNESS UK",
    },
  },
  {
    video: {
      videoId: "sNf0o51-l7o&ab_channel=DYNAMIXFITNESSUK",
      title: "Tricep Assisted Dip Machine",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/sNf0o51-l7o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBGGnzonNVrZWag6ORqai5wXmdxQQ",
        },
      ],
      channelName: "Somehting else",
    },
  },
  {
    video: {
      videoId: "sNf0o51-l7o&ab_channel=DYNAMIXFITNESSUK",
      title: "Tricep Assisted Dip Machine",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/sNf0o51-l7o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBGGnzonNVrZWag6ORqai5wXmdxQQ",
        },
      ],
      channelName: "gargrgraegraeg",
    },
  },
  {
    video: {
      videoId: "sNf0o51-l7o&ab_channel=DYNAMIXFITNESSUK",
      title: "Tricep Assisted Dip Machine",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/sNf0o51-l7o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBGGnzonNVrZWag6ORqai5wXmdxQQ",
        },
      ],
      channelName: "Hellow",
    },
  },
];

export const data = [
  {
    id: "1234",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "0000",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
];

export const data2 = [
  {
    id: "1234",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "0000",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "5555",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "6666",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "7777",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "8888",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "9999",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "1111",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "2222",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "3333",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "4563",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "9874",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
];

export const data3 = [
  {
    id: "1234",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "0000",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "5555",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "6666",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "7777",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "8888",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "9999",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "1111",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "2222",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "3333",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "4563",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "9874",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "1234",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "0000",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "5555",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "6666",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "7777",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "8888",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "9999",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "1111",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "2222",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "3333",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "4563",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "9874",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "1234",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "0000",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "5555",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "6666",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "7777",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "8888",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "9999",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "1111",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "2222",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "3333",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "4563",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "9874",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "1234",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "0000",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "5555",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "6666",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "7777",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "8888",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "9999",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "1111",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "2222",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "3333",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
  {
    id: "4563",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "triceps",
    name: "Assisted Triceps Dip",
    equipment: "body weight",
  },
  {
    id: "9874",
    gifUrl: gif,
    bodyPart: "Upper Arms",
    target: "Thigh",
    name: "Squats",
    equipment: "Band",
  },
];
